name: news
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.26.0
  http_parser: ^4.0.0
  http: ^0.13.1
  intl: ^0.17.0
  jiffy: ^4.1.0
  firebase_core: ^1.0.3
  firebase_auth_web: ^1.0.5
  firebase_auth: ^1.0.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  formz: ^0.4.0
  pedantic: ^1.11.0
  equatable: ^2.0.0
  meta: ^1.3.0
  font_awesome_flutter: ^9.0.0
  path_provider: ^2.0.1
  uuid: 3.0.4
  flutter_launcher_icons: ^0.9.0
  social_share: ^2.1.1
  flutter_social_content_share: ^1.0.0
  shared_preferences: ^2.0.5
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  url_launcher: ^6.0.3
  image_picker: ^0.7.4
  connectivity_plus: ^1.0.1
  provider: ^5.0.0
  flutter_slidable: ^0.6.0
  share: ^2.0.1
  google_sign_in: ^5.0.2
  google_fonts: ^2.0.0
  cached_network_image: ^3.0.0
  firebase_analytics: ^8.0.2
  firebase_crashlytics: ^2.0.2
  flutter_flavor: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

dev_dependencies:
  hive_generator: ^1.0.1
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/splash.jpg
    - assets/placeholder.png
    - assets/langs/
    - assets/user_placeholder.png
    - google_fonts/