var countries = {
  'all': 'All',
  'rs': 'Serbia',
  'ar': 'Argentina',
  'gr': 'Greece',
  'nl': 'Netherlands',
  'za': 'South Africa',
  'au': 'Australia',
  'hk': 'Hong Kong',
  'nz': 'New Zealand',
  'kr': 'South Korea',
  'at': 'Austria',
  'hu': 'Hungary',
  'ng': 'Nigeria',
  'se': 'Sweden',
  'be': 'Belgium',
  'in': 'India',
  'no': 'Norway',
  'ch': 'Switzerland',
  'br': 'Brazil',
  'id': 'Indonesia',
  'ph': 'Philippines',
  'tw': 'Taiwan',
  'bg': 'Bulgaria',
  'ie': 'Ireland',
  'pl': 'Poland',
  'th': 'Thailand',
  'ca': 'Canada',
  'il': 'Isreal',
  'pt': 'Portugal',
  'tr': 'Turkey',
  'cn': 'China',
  'it': 'Italia',
  'ro': 'Romania',
  'ae': 'UAE',
  'co': 'Colombia',
  'jp': 'Japan',
  'ru': 'Russia',
  'ua': 'Ukraine',
  'cu': 'Cuba',
  'lv': 'Latvia',
  'sa': 'Saudi Arabia',
  'gb': 'United Kingdom',
  'cz': 'Czech Republic',
  'lt': 'Lithuania',
  'us': 'United States',
  'eg': 'Egypt',
  'my': 'Malaysia',
  'sg': 'Singapore',
  've': 'Venezuela',
  'fr': 'France',
  'mx': 'Mexico',
  'sk': 'Slovakia',
  'de': 'Germany',
  'ma': 'Morocco',
  'si': 'Slovenia',
};
